const jobs = [
  { name: "Software Developer", creditsRate: 37.5, emoji: "💻" },
  { name: "Graphic Designer", creditsRate: 30, emoji: "🎨" },
  { name: "Content Writer", creditsRate: 22.5, emoji: "📝" },
  { name: "Social Media Manager", creditsRate: 26.25, emoji: "📱" },
  { name: "Data Analyst", creditsRate: 33.75, emoji: "📊" },
  { name: "Video Editor", creditsRate: 28.125, emoji: "🎥" },
  { name: "Photographer", creditsRate: 26.25, emoji: "📸" },
  { name: "Marketing Specialist", creditsRate: 31.875, emoji: "📣" },
  { name: "Customer Support Representative", creditsRate: 18.75, emoji: "📞" },
  { name: "Translator", creditsRate: 24.375, emoji: "🌍" },
  { name: "Sales Representative", creditsRate: 30, emoji: "💼" },
  { name: "Event Planner", creditsRate: 28.125, emoji: "🎉" },
  { name: "Fitness Instructor", creditsRate: 22.5, emoji: "💪" },
  { name: "Chef", creditsRate: 33.75, emoji: "👨‍🍳" },
  { name: "Baker", creditsRate: 26.25, emoji: "🥐" },
  { name: "Barista", creditsRate: 20.625, emoji: "☕" },
  { name: "Personal Trainer", creditsRate: 30, emoji: "🏋️‍♂️" },
  { name: "Hair Stylist", creditsRate: 24.375, emoji: "💇" },
  { name: "Pet Groomer", creditsRate: 22.5, emoji: "🐶" },
  { name: "Gardener", creditsRate: 20.625, emoji: "🌿" },
  { name: "Game Developer", creditsRate: 35.625, emoji: "🎮" },
  { name: "Game Tester", creditsRate: 26.25, emoji: "🕹️" },
  { name: "Game Designer", creditsRate: 31.875, emoji: "🎲" },
  { name: "Linux System Administrator", creditsRate: 33.75, emoji: "🐧" },
  { name: "Network Engineer", creditsRate: 30, emoji: "🌐" },
  { name: "DevOps Engineer", creditsRate: 31.875, emoji: "🔧" },
  { name: "Database Administrator", creditsRate: 28.125, emoji: "🗄️" },
  { name: "Server Administrator", creditsRate: 30, emoji: "🖥️" },
  { name: "IT Security Specialist", creditsRate: 33.75, emoji: "🔒" },
  { name: "Cloud Architect", creditsRate: 31.875, emoji: "☁️" },
  { name: "Linux System Administrator", creditsRate: 33.75, emoji: "🐧" },
  { name: "Network Engineer", creditsRate: 30, emoji: "🌐" },
  { name: "DevOps Engineer", creditsRate: 31.875, emoji: "🔧" },
  { name: "Database Administrator", creditsRate: 28.125, emoji: "🗄️" },
  { name: "Server Administrator", creditsRate: 30, emoji: "🖥️" },
  { name: "IT Security Specialist", creditsRate: 33.75, emoji: "🔒" },
  { name: "Cloud Architect", creditsRate: 31.875, emoji: "☁️" },
  { name: "Linux Kernel Developer", creditsRate: 35.625, emoji: "🐧💻" },
  { name: "Linux Distribution Maintainer", creditsRate: 31.875, emoji: "📦🐧" },
  { name: "Linux System Engineer", creditsRate: 31.875, emoji: "🔩🐧" },
  { name: "Linux Network Administrator", creditsRate: 30, emoji: "🌐🐧" },
  { name: "Linux Security Analyst", creditsRate: 33.75, emoji: "🔒🐧" },
  {
    name: "Linux Virtualization Specialist",
    creditsRate: 31.875,
    emoji: "💻🐧",
  },
  { name: "Linux Storage Administrator", creditsRate: 30, emoji: "💾🐧" },
  { name: "Linux Web Server Administrator", creditsRate: 30, emoji: "🌐🐧" },
  { name: "Linux Automation Engineer", creditsRate: 31.875, emoji: "⚙️🐧" },
  {
    name: "Linux Desktop Support Specialist",
    creditsRate: 28.125,
    emoji: "🖥️🐧",
  },
  { name: "Linux Consultant", creditsRate: 33.75, emoji: "👩‍💼🐧" },
  { name: "Network Engineer", creditsRate: 30, emoji: "🌐" },
  { name: "Network Administrator", creditsRate: 28.125, emoji: "🔌🔧" },
  { name: "Network Security Engineer", creditsRate: 33.75, emoji: "🔒🔧" },
  { name: "Network Architect", creditsRate: 31.875, emoji: "🏛️🌐" },
  { name: "Wireless Network Engineer", creditsRate: 30, emoji: "📶🌐" },
  {
    name: "Network Operations Center (NOC) Technician",
    creditsRate: 26.25,
    emoji: "📡🔧",
  },
  { name: "Network Support Specialist", creditsRate: 26.25, emoji: "🔧📞" },
  { name: "Network Consultant", creditsRate: 33.75, emoji: "👩‍💼🌐" },
  { name: "Network Project Manager", creditsRate: 31.875, emoji: "👩‍💼📂🌐" },
  { name: "VoIP Engineer", creditsRate: 30, emoji: "☎️🌐" },
];

export default jobs;
